baseURL = "http://blog.allsunday.io/"
title = "allsunday"
theme = "journal"
defaultContentLanguage = "cn"
hasCJKLanguage = true

[params]
description = "allsunday."
githubUsername = "gfreezy"
tagline = "追求卓越成功会在不经意间追上你"
