keep_files:  ['.git','.svn']

# permalink:     date
paginate_path: ':num'
paginate:      25

safe:        true

defaults:
  -
    scope:
      path: "_posts"
      type: "post"
    values:
      layout: "post"
      author: "gfreezy"
