source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
gems:        []
# timezone:    nil
# encoding:    nil

future:      true
show_drafts: nil
limit_posts: 0
highlighter: pygments

relative_permalinks: true

# permalink:     date
paginate_path: ':num'
paginate:      25

markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        true
baseurl:     ""
url:         http://localhost:4000
lsi:         false

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
      author: "gfreezy"
